# /etc/searxng/settings.yml

# 1. Base settings: load defaults, then override
use_default_settings: true

# 2. Core instance settings
secret_key: "${SEARXNG_SECRET}"   # from .env, must differ from default
public_instance: false            # disable public‑only features
limiter: false                    # turn off built‑in rate limiting

# 3. Server binding (all interfaces)
server:
  bind_address: "0.0.0.0"
  port: 8888

# 4. Search API formats & languages
search:
  formats:
    - html
    - json
  languages:
    - all

# 5. Redis (used internally even if limiter is off)
redis:
  url: "${SEARXNG_REDIS_URL}"      # e.g. redis://unicorn-redis:6379/0

# 6. Outgoing HTTP settings
outgoing:
  request_timeout: 5.0
  pool_connections: 100
  pool_maxsize: 20

# 7. Custom Engines
engines:
  # — Brave Search via JSON API —
  brave_search:
    module: json_engine
    shortcut: bs
    name: "Brave Search"
    request:
      method: GET
      url: "https://api.search.brave.com/res/v1/web/search"
      params:
        q:   "{{ query }}"
        key: "{{ BRAVE_API_KEY }}"
    response:
      items:   "items"
      title:   "title"
      url:     "link"
      snippet: "description"

  # — Google Custom Search API —
  google_custom:
    module: json_engine
    shortcut: g
    name: "Google Custom Search"
    request:
      method: GET
      url: "https://www.googleapis.com/customsearch/v1"
      params:
        key: "{{ GOOGLE_API_KEY }}"
        cx:  "{{ GOOGLE_CX }}"
        q:   "{{ query }}"
    response:
      items:   "items"
      title:   "title"
      url:     "link"
      snippet: "snippet"

# 8. UI / Branding
ui:
  # customize static_path or templates_path here if you like
  # static_path: ""
  # templates_path: ""